Catalog_Films/FilmsCatalog/Models/Film.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FilmsCatalog.Models
{
    public class Film
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        [Required]
        public string CreatorId { get; set; }

        public User Creator { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Year { get; set; }

        public string Producer { get; set; }

        public string Path { get; set; }
    }
}

Catalog_Films/FilmsCatalog/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FilmsCatalog.Data;
using FilmsCatalog.Models;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Identity;
using FilmsCatalog.Services;

namespace FilmsCatalog.Controllers
{
    public class FilmsController : Controller
    {
        private static readonly HashSet<String> AllowedExtensions = new HashSet<String> { ".jpg", ".jpeg", ".png", ".gif" };

        private readonly ApplicationDbContext _context;

        private readonly UserManager<User> userManager;

        private readonly IHostingEnvironment hostingEnvironment;

        private readonly IUserPermissionsService userPermissions;

        public FilmsController(ApplicationDbContext context, UserManager<User> userManager, IUserPermissionsService userPermissions, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            this.userManager = userManager;
            this.userPermissions = userPermissions;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: Films
        public IActionResult Index(int? page)
        {
            int pageSize = 15;
            int pageNumber = (page ?? 1);

            var applicationDbContext = _context.Films.Include(f => f.Creator);
            return View(applicationDbContext.ToPagedList(pageNumber, pageSize));
        }

        // GET: Films/Create
        [Authorize]
        public IActionResult Create()
        {
            return this.View(new FilmCreateViewModel());
        }

        // POST: Films/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(FilmCreateViewModel model)
        {
            var user = await userManager.GetUserAsync(HttpContext.User);
            var fileName = Path.GetFileName(ContentDispositionHeaderValue.Parse(model.Poster.ContentDisposition).FileName.Trim('"'));
            var fileExt = Path.GetExtension(fileName);
            if (!AllowedExtensions.Contains(fileExt))
            {
                ModelState.AddModelError(nameof(model.Poster), "This file type is prohibited");
            }

            if (ModelState.IsValid)
            {
                var _film = new Film
                {
                    Name = model.Name,
                    Description = model.Description,
                    Year = model.Year,
                    Producer = model.Producer,
                    Creator = user,
                    CreatorId = user.Id
                };

                var posterPath = Path.Combine(hostingEnvironment.WebRootPath, "attachments", _film.Id.ToString("N") + fileExt);
                _film.Path = $"/attachments/{_film.Id:N}{fileExt}";
                using (var fileStream = new FileStream(posterPath, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                {
                    await model.Poster.CopyToAsync(fileStream);
                }

                _context.Add(_film);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Films/Details/5
        [Authorize]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Films
                .Include(f => f.Creator)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            if (userPermissions.CanEditFilm(film))
            {
                ViewBag.permission = true;
            }
            else ViewBag.permission = false;

            return View(film);
        }

        // GET: Films/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await this._context.Films
                .SingleOrDefaultAsync(m => m.Id == id);
            if (film == null || !this.userPermissions.CanEditFilm(film))
            {
                return NotFound();
            }

            var model = new FilmEditViewModel
            {
                Name = film.Name,
                Description = film.Description,
                Year = film.Year,
                Producer = film.Producer
            };

            return this.View(model);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid? id, FilmEditViewModel model)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var film = await this._context.Films
                .SingleOrDefaultAsync(m => m.Id == id);
            if (film == null || !this.userPermissions.CanEditFilm(film))
            {
                return this.NotFound();
            }

            var fileName = Path.GetFileName(ContentDispositionHeaderValue.Parse(model.Poster.ContentDisposition).FileName.Trim('"'));
            var fileExt = Path.GetExtension(fileName);
            if (!AllowedExtensions.Contains(fileExt))
            {
                ModelState.AddModelError(nameof(model.Poster), "This file type is prohibited");
            }

            if (this.ModelState.IsValid)
            {
                film.Name = model.Name;
                film.Description = model.Description;
                film.Year = model.Year;
                film.Producer = model.Producer;

                if (model.Poster != null)
                {
                    var posterPath = Path.Combine(hostingEnvironment.WebRootPath, "attachments", film.Id.ToString("N") + fileExt);
                    film.Path = $"/attachments/{film.Id:N}{fileExt}";
                    using (var fileStream = new FileStream(posterPath, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read))
                    {
                        await model.Poster.CopyToAsync(fileStream);
                    }
                }

                await this._context.SaveChangesAsync();
                return this.RedirectToAction("Index");
            }

            return this.View(model);
        }

        // GET: Films/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Films
                .Include(f => f.Creator)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null || !this.userPermissions.CanEditFilm(film))
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(Guid? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var film = await this._context.Films
                .SingleOrDefaultAsync(m => m.Id == id);

            if (film == null || !this.userPermissions.CanEditFilm(film))
            {
                return this.NotFound();
            }

            var posterPath = Path.Combine(this.hostingEnvironment.WebRootPath, "attachments", film.Id.ToString("N") + Path.GetExtension(film.Path));
            System.IO.File.Delete(posterPath);
            _context.Films.Remove(film);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Catalog_Films/FilmsCatalog/Views/Films/Create.cshtml
@model FilmsCatalog.Models.FilmCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Film</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producer" class="control-label"></label>
                <input asp-for="Producer" class="form-control" />
                <span asp-validation-for="Producer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poster" class="control-label"></label>
                <input asp-for="Poster" class="form-control" />
                <span asp-validation-for="Poster" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Catalog_Films/FilmsCatalog/Views/Films/Delete.cshtml
@model FilmsCatalog.Models.Film

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Film</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Creator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Creator.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Producer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Producer)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Catalog_Films/FilmsCatalog/Views/Films/Details.cshtml
@model FilmsCatalog.Models.Film
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@{
    ViewData["Title"] = "Details";
}

<h4>Фильм</h4>
<hr />
<table class="table">
    <tbody>
        <tr>
            <td width="200">
                <a asp-action="Details" asp-route-id="@Model.Id">
                    <img src="@Model.Path" width="200" height="300" />
                </a>
            </td>
            <td>
                <big><b><u>@Html.DisplayFor(model => model.Name) (@Html.DisplayFor(model => model.Year))</u></b></big>
                <br />
                реж. @Html.DisplayFor(model => model.Producer)
                <br />
                @Html.DisplayFor(model => model.Description)
            </td>
        </tr>
    </tbody>
</table>


<div>
    <a asp-action="Index">Назад</a>
</div>

Catalog_Films/FilmsCatalog/Views/Films/Edit.cshtml
@model FilmsCatalog.Models.FilmEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Film</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producer" class="control-label"></label>
                <input asp-for="Producer" class="form-control" />
                <span asp-validation-for="Producer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poster" class="control-label"></label>
                <input asp-for="Poster" class="form-control" />
                <span asp-validation-for="Poster" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Catalog_Films/FilmsCatalog/Views/Films/Index.cshtml
@model X.PagedList.IPagedList<FilmsCatalog.Models.Film>
@using X.PagedList;
@using X.PagedList.Mvc.Core;

@{
    ViewData["Title"] = "Index";
}

<table class="table">
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <b><big><a asp-action="Details" asp-route-id="@item.Id" style="color:#000000">@Html.DisplayFor(modelItem => item.Name) (@Html.DisplayFor(modelItem => item.Year))</a></big></b>
                </td>
            </tr>
        }
    </tbody>
</table>
<big>
    <div class="pagination">
        Страница
        @Html.PagedListPager(Model, page => Url.Action("Index", "Films", new { page }))
    </div>
</big>